### ISSUE TITLE
In the <Modal />, is there a way to set different transitions for the backdrop  between children ?

### ISSUE THREAD

**Issue by foisonocean** [react-bootstrap/react-overlays#136]

**Comment by jquense** [comment]
Yup, provide your own `Transition` component that does that

**Comment by foisonocean** [comment]
@jquense Sorry for my English, my question is how to set different transitions for the backdrop between children.

**Comment by jquense** [comment]
not srue what "children" means here, but you handle all animation via a Transition component. you can use css animations to target the things you want to animate. See the bootstrap css for an example. it uses a fade for the backdrop and a slide in for the Modal component

**Comment by foisonocean** [comment]
@jquense I want to set different transition between dialog and backdrop. But when I use the `transition` property in `<Modal />`, it set the same transition for the dialog and backdrop.

**Comment by jquense** [comment]
You can't specify a different Transition component for each, but you can have one component do both. see the react-bootstrap Modal as I mentioned above

**Comment by foisonocean** [comment]
@jquense I can't understand why react-bootstrap Modal can have two different transitions. Can you show me a more simple demo ?

**Comment by reywright** [comment]
@foisonocean I'm running into similar issues. To be honest, just take <Portal /> and <Transition /> from react-overlays and make your own modal. Not all modals for different sites are straightforward. Right now I'm going through the same thing where I want some sweet animations on my modal, but sometimes I don't want them on mobile... so that's when you come to the realization that you're an edge case, and then you just fork the library you're working on or you just start coding your own. It's not that difficult.

**Comment by jquense** [comment]
folks look at the bootstrap modal css. There ARE two different animations for the backdrop and dialog already. 

And don't jsut roll your own Modal. There is a reason why react-overlays has a separate Component from Portal for Modal. Its because building modals correctly is not actually easy.
