### ISSUE TITLE
Style _overlayTarget

### ISSUE THREAD

**Issue by AvraamMavridis** [react-bootstrap/react-overlays#171]
Is it a way to style the `_overlayTarget` ?

I am using the overlay component like:

```
          <Overlay
            container={ () => document.querySelector('body') }
            show={ this.state.show }
            onHide={ () => this.setState({ show: false }) }
            placement={ this.state.placement }
            target={ () => findDOMNode(this.refs.target) }>
            <TooltipContent placement={ this.props }
              className={ className }
              content={ content }
              arrowClassName={ arrowClassName } />
          </Overlay>
```

There is an extra div creating around the Tooltip content that I guess comes from https://github.com/react-bootstrap/react-overlays/blob/master/src/Portal.js#L54

So my component is being rendered like:

![screen shot 2017-04-24 at 14 36 52](https://cloud.githubusercontent.com/assets/283690/25337387/fb7b533c-28fb-11e7-90ed-eff6ad35a16b.png)

And since I am appending to body, and I cannot pass any class or styling to this `div` its impossible to style it. If pass normal node as child of the component (without creating an extra dumb component), like:

```
          <Overlay
            container={ () => document.querySelector('body') }
            show={ this.state.show }
            onHide={ () => this.setState({ show: false }) }
            placement={ this.state.placement }
            target={ () => findDOMNode(this.refs.target) }>
            <div>
                 Some content
            </div>
          </Overlay>
```

I can style it properly but I am getting the unknown props error

`Unknown props `placement`, `arrowOffsetLeft`, `arrowOffsetTop`, `positionLeft`, `positionTop` on <div> tag.
`

Related to https://github.com/react-bootstrap/react-overlays/issues/167

So, my question is, is there any way to pass a class or style to this extra div?

**Comment by jquense** [comment]
> So, my question is, is there any way to pass a class or style to this extra div?

No, but this div is completely non presentational, there shouldn't be any styles on it. it only exists as a implementation detail of the Portal.

**Comment by AvraamMavridis** [comment]
>  there shouldn't be any styles on it

I agree, but it breaks the styling of the children even if it doesn't have styling itself, since many css properties behave differently depending on the parent. e.g. in my case setting the `position` attribute.

**Comment by ajbeaven** [comment]
While I agree that this wrapping div shouldn't typically be styled, there are cases where it is necessary. Take the following use case:

```
<span>Don't</span>
<span ref={el => {this.trigger = el}}>Break</span>
<span>Me</span>

<Overlay 
	target={this.trigger}
	container={this.trigger}
	show={true}>

	<Tooltip id="tooltip>But it does</Tooltip>
</Overlay>
```

In the example above, because the container element is inline, the overlay div that is added breaks the flow:

![image](https://user-images.githubusercontent.com/657201/28144936-9f4a7d80-67c2-11e7-96d9-f2c849184766.png)

Without any way of modifying this wrapping div (either by specifying `tagName` or `style` props), then there doesn't seem to be a good way to work around the problem above.

**Comment by taion** [comment]
I'm closing this for staleness.

Note that in the case above for e.g. a tooltip, you most likely don't need a portal at all – just use `<Position>` to position the tooltip.

**Comment by ajbeaven** [comment]
I understand why this is being closed but I don't see reference to a `<Position>` component anywhere...?

**Comment by jquense** [comment]
https://react-bootstrap.github.io/react-overlays/#position

**Comment by ajbeaven** [comment]
Ahh sorry - was looking at the react-bootstrap docs. Also, I wasn't clear that the code above was just a simplified example. In the real app I'm setting toggling visibility based on a few things, hence the usage of `<Overlay>`.

All that aside, I somewhat disagree that this shouldn't be considered due to the wrapping div being "non-presentational". While in theory that is the case, in practice, the div _does_ affect presentation (as shown in my example). Perhaps though you're happy with using workarounds like the one shown in my example - in which case, yay now it's somewhat documented :)
