### ISSUE TITLE
Trouble with the AutoAffix example

### ISSUE THREAD

**Issue by TheSavior** [react-bootstrap/react-overlays#172]
I have been having trouble getting the AutoAffix example from the docs working. I made a minimal jsfiddle that is essentially just the code from the docs. Is there something obvious here that I'm missing or forgetting?

https://jsfiddle.net/69z2wepo/76872/

Even if it was a problem with the output box scrolling instead of the entire document, just viewing that one iframe in a new tab doesn't get the box to affix.

**Comment by taion** [comment]
You appear to have attempted to bundle this package yourself via wzrd.in for your example. That doesn't work, and instead triggers the React errors you should observe in your console from your example, which arise because of the incorrect way in which you attempted to create an ad-hoc bundle for this library.

**Comment by TheSavior** [comment]
We had this problem at first in our actual codebase. I'd like to reproduce it in a way that we can share it easily. Clearly the jsfiddle with wzrd.in wasn't the right approach. Do you have a better recommendation for how you'd like a reproducible test case?
