### ISSUE TITLE
Modal does not implement proper focus trapping

### ISSUE THREAD

**Issue by jeffredodd** [react-bootstrap/react-overlays#191]
While developing a custom `role=dialog` component for another webapp, I noticed react-overlays Modal is not currently performing focus trapping correctly. While focus on the page can only hit tabbable modal elements, it is still allowed to exit the dialog into the browser. Per the WAI, this appears to not be suggested behavior. 

Actual: User can tab outside modal into browser (In this case Chrome)
Expected: User should not be able to tab outside of modal. 

https://www.w3.org/WAI/GL/wiki/Using_ARIA_role%3Ddialog_to_implement_a_modal_dialog_box#Note_on_focus_management

**Comment by taion** [comment]
We covered this before in #91, but per that example, it looks like we could just look at `event.target` instead of trying to read `activeElement`? Is there a reason we don't just do that?

**Comment by jeffredodd** [comment]
So the issue I believe is that the user can tab outside of the modal into the native browser. Per the WAI-ARIA best practices guideline on tabbing in a `role='dialog'` element...

`If focus is on the last tabbable element inside the dialog, moves focus to the first tabbable element inside the dialog.`

https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal

**Comment by jquense** [comment]
I've talked to bunch of folks about this. The question is whether focus should cycle like it would natively in a document (e.g. last element, to url bar, to first element) or not exit the window at all. There wasn't a clear consensus but most said that mimicking the browser behavior (e.g. full cycle through to browser chrome) is "more" correct.  I don't have a strong opinion about this, but the current behavior isn't a "bug" in the technical sense since i looked at both behaviors and intentionally chose this one.

**Comment by jeffredodd** [comment]
So after doing a bunch of research and attending training from the folks at WebAim both options are valid. However trapping the user inside the webpage would require them to use a shortcut to access the address bar if tab functionality is disabled. I'll update my code to reflect this and can close this issue. Thanks for the feedback @jquense.

**Comment by taion** [comment]
Thank you for taking the time to look into this.
