### ISSUE TITLE
Export as an UMD library for bower

### ISSUE THREAD

**Issue by dfournier** [react-bootstrap/react-overlays#26]
Hi!

Exporting react-bootstrap as an UMD lib on bower is such a good thing for people not using last generation tolling tools. I took the liberty to create [react-overlays-bower](https://github.com/dfournier/react-overlays-bower) and publish it on bower.

Tell me if you want the ownership of the repo and integrate automatically new versions in your release process.

Best,
David

**Comment by taion** [comment]
Please don't do that.

It means that to change the repo into something under this org, we'd need to delete-and-recreate the Bower repo, which will break everyone who already has it installed until they manually clear their caches.

**Comment by dfournier** [comment]
Sorry, I unregistered the package on Bower. Can I at least keep the repo?

**Comment by dfournier** [comment]
Actually I don't need, I had to build a custom version. I'm really sorry about the mess.

**Comment by bdkent** [comment]
Any chance of getting `react-overlays` on bower?

**Comment by Bendico** [comment]
I am also using bower. I'm using react-bootstrap in my application and I need react-overlays to play along with it. (Because I need the Affix component, which unfortunately is not part of react-bootstrap). Any chance of getting a package for it? Or maybe dfournier could give me a hint on how to build my own package (react-overlays.js)?
