### ISSUE TITLE
rootClose using React-Tap-Event-Plugin

### ISSUE THREAD

**Issue by Stenerson** [react-bootstrap/react-overlays#64]
When using [react-tap-event-plugin](https://github.com/zilverline/react-tap-event-plugin) and `rootClose={true}` the overlay opens and closes immediately. I've spent most of the day in my Chrome debugger but I can't figure out why it works as expected when my target uses `onClick` and it closes immediately when my target uses `onTouchTap`.

Here's what my component's `render()` function is returning:

``` javascript
<button
  className={classnames("btn",{"btn-primary": this.state.open})}
  onTouchTap={this._toggleOpen}
  ref="target"
>
  Open Overlay
  <Overlay
    show={this.state.open}
    onHide={() => this.setState({ open: false })}
    rootClose={true}
    placement={this.props.placement}
    target={() => ReactDOM.findDOMNode(this.refs.target)}
  >
    /* Some Overlay content... */
  </Overlay>
</button>
```

Honestly I'm not sure if this is an issue with react-overlays or not. I did see an [old issue](https://github.com/react-bootstrap/react-bootstrap/issues/831) in react-bootstrap that indicated the React-Tap-Event-Plugin _should_ work so I thought I'd start here.

As a workaround I'm just using `onClick` for my Overlay triggers but as you know it has a very sluggish feel on mobile devices, especially since the rest of the app is using `onTouchTap`.

Any ideas? Thanks!

**Comment by taion** [comment]
This sounds like an inconsistency between the component event handling and the backdrop event handling. Compare https://github.com/react-bootstrap/react-overlays/blob/92171fb806719aa37f063b46f174508fa254836f/src/RootCloseWrapper.js#L104 and https://github.com/react-bootstrap/react-overlays/blob/92171fb806719aa37f063b46f174508fa254836f/src/RootCloseWrapper.js#L51. Perhaps it ought to be possible to control the events injected in `<RootCloseWrapper>`?

**Comment by dahjelle** [comment]
I believe I'm running into this issue while using [react-fastclick](https://github.com/JakeSidSmith/react-fastclick): the react-bootstrap `DropdownButton` opens and closes immediately. I'm able to reproduce this in Chrome's mobile device simulator where touch events rather than mouse events can be triggered.

In my case, the `react-fastclick` code rewrites `touch` events as `click` events when there is an `onClick` handler present. That part seems to work fine.

The problem is that the `onClick` event added to the `document` in https://github.com/react-bootstrap/react-overlays/blob/92171fb806719aa37f063b46f174508fa254836f/src/RootCloseWrapper.js#L51 **also** fires, closing the dropdown almost immediately. (I'm guessing 300 ms later, though I haven't timed it.) Since this event handler is a native browser event handler, `react-fastclick` doesn't know anything about it.

This is presumably related to https://github.com/JakeSidSmith/react-fastclick/issues/30, but it isn't clear to me which library the problem is in, or if cooperation is needed for them to work together.

Incidentally, a separate solution to this might be a different fastclick library. Does `react-bootstrap` have one they suggest?

**Comment by dahjelle** [comment]
Here's my current hypothesis: `react-fastclick` mutates the **React** event to make the click event happen more quickly, but doesn't do anything to the native browser events. Normally, this works fine, but in the case of `react-overlays` the `componentDidMount` attaches event listeners for a `click` on `document`. Without `react-fastclick`, this works as expected. With `react-fastclick`, however, the overlay and the event listeners are added, and, then, 300 ms later, the native click event (the "slow" click) fires, closing the dropdown.

I'm currently thinking that this needs to be fixed in `react-fastclick`, but perhaps `react-overlays` needs some workarounds, too, since this happens with multiple fastclick libraries?

**Comment by Stenerson** [comment]
@dahjelle That seems consistent with what I remember observing using `react-tap-event-plugin`. It's been a while since I've looked at this in detail but I remember thinking it was odd that there were two click events when using (in my case) `onTouchTap`.

**Comment by Stenerson** [comment]
I tested this after PR #95 (`v0.6.6` to be exact) using `mousedown` and `click` and it's still doing the same thing. 

I'm surviving by using `onClick` rather than `onTouchTap` for overlays but the mobile delay is still a bit off-putting.

**Comment by Stenerson** [comment]
Closing this as I won’t be able to provide further updates and using `onClick` is a pretty viable option now that it’s possible to remove touch delays on the most used mobile browsers.
